// data.js

window.lessonsData = [
  {
    id: 1,
    title:
      "Прості рівняння з малюнками та без           (без переходу через десяток)",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/simple-equations.html",
    subject_code: "math_general",
    category: "test",
    author: "Даша",
  },
  {
    id: 2,
    title:
      "Знаходження невідомого доданка             (без переходу через десяток)",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/тест на рівняння.html",
    subject_code: "math_general",
    category: "test",
    author: "Даша",
  },
  {
    id: 3,
    title: "§9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест Степінь із цілим показником.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 4,
    title: "§10. Властивості степеня Тест",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/властивості степеня тест.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 5,
    title: "§11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест/Стандартний вигляд числа Тест1.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 7,
    title: "§13. Парабола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест Парабола.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 8,
    title: "§14. Арифметичний квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест Квадратний корінь.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 9,
    title: "§15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест Квадратний корінь.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 10,
    title: "§16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Тест/Тест корінь квадрат.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 201,
    title: "Перехід через десяток Додавання",
    grade: 2,
    topic: "Математика",
    link: "math_general/2/Перехід через десяток Додавання.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 501,
    title: "Rechenausdrücke",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Rechenausdrücke.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 502,
    title: "Mathematik-Test 5. Klasse (Deutschland)",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Zahlen und Rechnen.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 503,
    title: "Schriftliches Rechnen",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/В стовбчик.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 712,
    title: "Розклад многочлена на множники",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/Розклад многочлена на множники.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },

  {
    id: 8009,
    title: "§9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Урок Степінь із цілим показником.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8010,
    title: "§10. Властивості степеня із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Урок Властивості степеня.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8011,
    title: "§11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Урок/Урок Стандартний вигляд числа.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8012,
    title: "§12. Функція y = k/x",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Урок Гіпербола.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8013,
    title: "§13. Функція y = x² (Парабола)",
    grade: 8,
    topic: "Алгебра",
    subject_code: "algebra",
    link: "algebra/8/Урок Парабола.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8014,
    title: "§14. Арифметичний квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    subject_code: "algebra",
    link: "algebra/8/Урок Квадратний корінь.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8015,
    title: "§15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    subject_code: "algebra",
    link: "algebra/8/Урок Числові множини.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8016,
    title: "§16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    subject_code: "algebra",
    link: "algebra/8/Урок/Урок корінь квадрат.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8100,
    title: "Геометрія: Тренажер Логічного Мислення",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/Геометрія - пояснення логіки доведень.html",
    subject_code: "geometry",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8101,
    title: "Трапеція",
    grade: 8,
    topic: "Геометрія",
    subject_code: "geometry",
    link: "geometry/8/Трапеція.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 9005,
    title: "Рівняння прямої",
    grade: 9,
    topic: "Геометрія",
    subject_code: "geometry",
    link: "geometry/9/Рівняння прямої.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 18009,
    title: "ДЗ: §9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Степінь із цілим показником.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18010,
    title: "ДЗ: §10. Властивості степеня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Властивості степеня.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18011,
    title: "ДЗ: §11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня/Домашня Стандартний вигляд числа.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18012,
    title: "ДЗ: §12. Гіпербола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Гіпербола.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18013,
    title: "ДЗ: §13. Парабола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Парабола.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18014,
    title: "ДЗ: §14. Квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Квадратний корінь.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18015,
    title: "ДЗ: §15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня Числові множини.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 18016,
    title: "ДЗ: §16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Домашня/Домашня корінь квадрат.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: 400601,
    title: "Відсоткові розрахунки",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 400601,
    title: "Вадим Урок1",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим1.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 400602,
    title: "Вадим Урок2",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим2.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 400603,
    title: "Вадим Урок3",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим3.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 400604,
    title: "Вадим Урок4",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим4.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401779,
    title: "Функції Настя",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Функції Настя Соніна.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401780,
    title: "Функції Настя телефон",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Функції Настя Соніна телефон.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401000,
    title: "Настя Урок1",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя1.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401001,
    title: "Настя Урок2",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя2.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401002,
    title: "Настя Урок3",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя3.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 401003,
    title: "Настя Урок4",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя4.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402100,
    title: "Соніна Маринка учить дроби",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринкка/Дроби_маринка.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402101,
    title: "Соніна Маринка учить дроби2",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/gguv.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402102,
    title: "Маринка Урок1",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка1.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402103,
    title: "Маринка Урок2",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка2.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402104,
    title: "Маринка Урок3",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка3.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 402105,
    title: "Маринка Урок4",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка4.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
];
