// data.js

window.lessonsData = [
  {
    id: 1,
    title: "Прості рівняння (без переходу)",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/simple-equations.html",
    subject_code: "math_general",
    category: "test",
    author: "Даша",
  },
  {
    id: 2,
    title: "Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Стандартний вигляд числа Тест1.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 4,
    title: "Степінь з від'ємним показником. Частина 1",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/power-part1.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 7,
    title: "Властивості степеня. Частина 2 (Дроби)",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/power-part2.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: 300,
    title: "Геометрія: Тренажер Логічного Мислення",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/Геометрія - пояснення логіки доведень.html",
    subject_code: "geometry",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 501,
    title: "Rechenausdrücke",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Rechenausdrücke.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 712,
    title: "Розклад многочлена на множники",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/Розклад многочлена на множники.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 777,
    title: "Соніна Маринка учить дроби",
    grade: 8,
    topic: "Математика",
    link: "math_general/6/Дроби_маринка.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 778,
    title: "Соніна Маринка учить дроби2",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/gguv.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 779,
    title: "Функції Настя",
    grade: 8,
    topic: "Математика",
    link: "algebra/9/Функції Настя Соніна.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: 8010,
    title: "§10. Властивості степеня із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson-powers.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8011,
    title: "§11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Стандартний вигляд числа.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8012,
    title: "§12. Функція y = k/x",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/Гіпербола.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8013,
    title: "§13. Функція y = x² (Парабола)",
    grade: 8,
    topic: "Функції",
    subject_code: "algebra",
    link: "algebra/8/parabola-lesson.html",
    category: "lesson",
    author: "Даша",
  },
  {
    id: 8101,
    title: "Трапеція",
    grade: 8,
    topic: "Геометрія",
    subject_code: "geometry",
    link: "geometry/8/Трапеція.html",
    category: "lesson",
    author: "Даша",
  },
];
