// data.js

window.lessonsData = [
  // ==========================================
  // 2 КЛАС (Математика) - Автор: Даша
  // ==========================================
  {
    id: "math-2-eq-simple",
    
    title: "Прості рівняння з малюнками та без (без переходу через десяток)",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/simple-equations.html",
    subject_code: "math_general",
    category: "test",
    author: "Даша",
  },
  {
    id: "math-2-eq-find-sum",
    title: "Знаходження невідомого доданка (без переходу через десяток)",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/тест на рівняння.html",
    subject_code: "math_general",
    category: "test",
    author: "Даша",
  },
  {
    id: "math-2-lesson-add-tens",
    title:
      "Урок1. Перехід через десяток. Додавання двоцифрового числа до одноцифрового",
    grade: 2,
    topic: "Математика",
    link: "math_general/2/factoring_numbers_addition.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-lesson-sub-tens",
    title:
      "Урок2. Перехід через десяток. Віднімання від двоцифрового числа одноцифрового",
    grade: 2,
    topic: "Математика",
    link: "math_general/2/factoring_numbers_subtraction.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-mix-ops-100",
    title:
      "Додавання та віднімання в межах 100 (з переходом та без) + рівняння",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/mixed_operations_within_100.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-space-mission",
    title: "Космічна Місія: Арифметика в межах 100",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/math_space_mission.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-investigation",
    title: "Гра у детектива: Задачі з обчисленням у межах 100",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/investigation_lesson.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-toy-game-lesson",
    title: "Приклади і магазин розмальовок",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/lesson_and_toy_market.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-bear-lesson",
    title: "Накорми ведмедиків!",
    grade: 2,
    topic: "Арифметика",
    link: "math_general/2/1-bear-lesson.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-2-hw-01",
    title: "Домашня1",
    grade: 2,
    topic: "Математика",
    link: "math_general/2/HW_factoring_numbers_addition.html",
    subject_code: "math_general",
    category: "homework",
    author: "Даша",
  },
  {
    id: "math-2-hw-02",
    title: "Домашня2",
    grade: 2,
    topic: "Математика",
    link: "math_general/2/mixed_operations_within_100_hw.html",
    subject_code: "math_general",
    category: "homework",
    author: "Даша",
  },

  // ==========================================
  // 5 КЛАС (Математика) - Автор: Даша
  // ==========================================
  {
    id: "math-5-expr-de",
    title: "Rechenausdrücke",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Rechenausdrücke.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-test-de",
    title: "Mathematik-Test 5. Klasse (Deutschland)",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Zahlen und Rechnen.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-column-calc",
    title: "Schriftliches Rechnen",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/В стовбчик.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-hw-numbers",
    title: "Homework_zahlen",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Homework_zahlen.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-cw-numbers",
    title: "Classwork_zahlen",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/Classwork_zahlen.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-control-sim",
    title:
      "Контрольна з теми: додавання віднімання ділення та множення в стовбчик",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/test_simulator.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-control-sim1",
    title:
      "Контрольна з теми: додавання віднімання ділення та множення в стовбчик. Варіант Б",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/test_simulator1.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-control-sim2",
    title:
      "Контрольна з теми: додавання віднімання ділення та множення в стовбчик. Варіант В",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/test_simulator2.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-column-mult",
    title: "Множення чисел у стовпчик",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/column_multiplication.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-5-cyber-lesson",
    title: "Cyber-Mathematik: Logik, Strukturen und Algorithmen",
    grade: 5,
    topic: "Математика",
    link: "math_general/5/lesson1.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-6-rat-op",
    title: "Додавання, віднімання, множення та ділення раціональних чисел",
    grade: 6,
    topic: "Алгебра",
    link: "math_general/6/lesson/rational-numbers-operations.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-6-eq-intro",
    title: "10. Рівняння",
    grade: 6,
    topic: "Алгебра",
    link: "math_general/6/lesson/lesson-one.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  // ==========================================
  // 7 КЛАС (Алгебра) - Автор: Даша
  // ==========================================
  {
    id: "alg-7-eq-intro",
    title: "Загальні відомості про рівняння",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/lesson/01-equations-intro.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-7-eq-linear",
    title: "Лінійні рівняння з однією змінною",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/lesson/02-linear-equations.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-7-poly-sum-diff",
    title: "Додавання та віднімання многочленів",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/lesson/11-polinomials-addition-subtraction.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-7-polynomials",
    title: "Розклад многочлена на множники",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/Розклад многочлена на множники.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "math-probne",
    title: "Пробне",
    grade: 7,
    topic: "Алгебра",
    link: "algebra/7/lesson/probbne7.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },

  // ==========================================
  // 8 КЛАС (Алгебра - ТЕСТИ) - Автор: Даша
  // ==========================================
  {
    id: "alg-8-base",
    title: "Пробний урок Низького рівня до 1 семестру",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson_base.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-09",
    title: "Тест: §9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/09-2-integer-exponents.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-10",
    title: "Тест: §10. Властивості степеня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/10-exponent-properties.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-11",
    title: "Тест: §11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/11-standard-form.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-12",
    title: "Тест: §12. Гіпербола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/12-inverse-proportion-function.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-13",
    title: "Тест: §13. Парабола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/13-function-x-squared.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-14",
    title: "Тест: §14. Арифметичний квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/14-arithmetic-square-root.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-15",
    title: "Тест: §15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/15-number-sets.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-16",
    title: "Тест: §16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/16-root-identity-and-equations.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-11-12-mix",
    title: "Тестування §11-12",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/test-11-12.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-hw-review-1-11",
    title: "Повторення тем 1-11",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/test-1-11.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  {
    id: "alg-8-test-17",
    title: "Тест: §17. Властивості арифметичного квадратного кореня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/test/17-arithmetic-square-root-properties.html",
    subject_code: "algebra",
    category: "test",
    author: "Даша",
  },
  // ==========================================
  // 8 КЛАС (Алгебра - УРОКИ) - Автор: Даша
  // ==========================================
  {
    id: "alg-8-lesson-09",
    title: "§9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/09-integer-exponents.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-10",
    title: "§10. Властивості степеня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/10-exponent-properties.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-11",
    title: "§11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/11-standard-form.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-12",
    title: "§12. Гіпербола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/12-inverse-proportion-function.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-13",
    title: "§13. Парабола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/13-function-x-squared.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-14",
    title: "§14. Квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/14-arithmetic-square-root.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-15",
    title: "§15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/15-number-sets.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-16",
    title: "§16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/16-root-identity-and-equations.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "alg-8-lesson-17",
    title: "§17. Властивості арифметичного квадратного кореня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/lesson/17-arithmetic-square-root-properties.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Даша",
  },

  // ==========================================
  // 8 КЛАС (Алгебра - ДОМАШНІ) - Автор: Даша
  // ==========================================
  {
    id: "alg-8-hw-09",
    title: "ДЗ: §9. Степінь із цілим показником",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/09-integer-exponents.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-10",
    title: "ДЗ: §10. Властивості степеня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/10-exponent-properties.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-11",
    title: "ДЗ: §11. Стандартний вигляд числа",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/11-standard-form.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-12",
    title: "ДЗ: §12. Гіпербола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/12-inverse-proportion-function.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-13",
    title: "ДЗ: §13. Парабола",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/13-function-x-squared.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-14",
    title: "ДЗ: §14. Квадратний корінь",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/14-arithmetic-square-root.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-15",
    title: "ДЗ: §15. Множина. Числові множини",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/15-number-sets.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-16",
    title: "ДЗ: §16. Тотожність (√a)² = a",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/16-root-identity-and-equations.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },
  {
    id: "alg-8-hw-17",
    title: "ДЗ: §17. Властивості арифметичного квадратного кореня",
    grade: 8,
    topic: "Алгебра",
    link: "algebra/8/homework/17-arithmetic-square-root-properties.html",
    subject_code: "algebra",
    category: "homework",
    author: "Даша",
  },

  // ==========================================
  // 8 КЛАС (Геометрія - Тести) - Автор: Даша
  // ==========================================

  {
    id: "geom-8-test-001",
    title: "§0. Повторення: кути та трикутники",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/test/001-angles-triangles.html",
    subject_code: "geometry",
    category: "test",
    author: "Даша",
  },
  {
    id: "geom-8-test-09",
    title: "§9. Середня лінія трикутника",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/test/9-triangle-midline.html",
    subject_code: "geometry",
    category: "test",
    author: "Даша",
  },

  // ==========================================
  // 8 КЛАС (Геометрія - Уроки) - Автор: Даша
  // ==========================================
  {
    id: "geom-8-lesson-001",
    title: "§0. Повторення: кути та трикутники",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/lesson/001-angles-triangles.html",
    subject_code: "geometry",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "geom-8-lesson-09",
    title: "§9. Середня лінія трикутника",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/lesson/9-triangle-midline.html",
    subject_code: "geometry",
    category: "lesson",
    author: "Даша",
  },
  // ==========================================
  // 8 КЛАС (Геометрія - Домашні) - Автор: Даша
  // ==========================================
  {
    id: "geom-8-homework-001",
    title: "ДЗ: §0. Повторення: кути та трикутники",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/homework/001-angles-triangles.html",
    subject_code: "geometry",
    category: "homework",
    author: "Даша",
  },
  {
    id: "geom-8-homework-09",
    title: "ДЗ: §9. Середня лінія трикутника",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/homework/9-triangle-midline.html",
    subject_code: "geometry",
    category: "homework",
    author: "Даша",
  },

  // ==========================================
  // 8 КЛАС (Геометрія) - Автор: Даша
  // ==========================================
  {
    id: "geom-8-logic",
    title: "Геометрія: Тренажер Логічного Мислення",
    grade: 8,
    topic: "Геометрія",
    link: "geometry/8/Геометрія - пояснення логіки доведень.html",
    subject_code: "geometry",
    category: "lesson",
    author: "Даша",
  },
  {
    id: "geom-8-trapezoid",
    title: "Трапеція",
    grade: 8,
    topic: "Геометрія",
    subject_code: "geometry",
    link: "geometry/8/Трапеція.html",
    category: "lesson",
    author: "Даша",
  },
  // ==========================================
  // 9 КЛАС (Геометрія) - Автор: Даша
  // ==========================================
  {
    id: "geom-9-line-eq",
    title: "Рівняння прямої",
    grade: 9,
    topic: "Геометрія",
    subject_code: "geometry",
    link: "geometry/9/Рівняння прямої.html",
    category: "lesson",
    author: "Даша",
  },

  // ==========================================
  // 6 КЛАС (Математика) - Автор: Соня
  // ==========================================
  {
    id: "math-6-sonya-percents",
    title: "Відсоткові розрахунки",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-vadim-01",
    title: "Вадим Урок1",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим1.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
   {
    id: "math-6-vadim-domashnie",
    title: "ДЗ",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/dzvadym.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-vadim-02",
    title: "Вадим Урок2",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим2.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-vadim-03",
    title: "Вадим Урок3",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим3.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-vadim-04",
    title: "Вадим Урок4",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим4.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-droby",
    title: "Дроби Всеволод",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Всеволод.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-1rozdil",
    title: "Модуль",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Вадим5.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "math-6-rivniannyia",
    title: "Рівняння",
    grade: 6,
    topic: "Математика",
    link: "math_general/6/Вадим/Всеволод2.html",
    subject_code: "math_general",
    category: "lesson",
    author: "Соня",
  },
  // ==========================================
  // 8 КЛАС (Алгебра - Маринка/Соня) - Автор: Соня
  // ЦІ УРОКИ ТЕПЕР В КІНЦІ СПИСКУ 8 КЛАСУ
  // ==========================================
  {
    id: "alg-8-sonya-fractions-1",
    title: "Соніна Маринка учить дроби",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринкка/Дроби_маринка.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
   {
    id: "alg-8-sonya-",
    title: "Дз",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/dzmarina.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-8-sonya-fractions-2",
    title: "Соніна Маринка учить дроби2",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/gguv.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-8-marinka-01",
    title: "Маринка Урок1",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка1.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-8-marinka-02",
    title: "Маринка Урок2",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка2.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-8-marinka-03",
    title: "Маринка Урок3",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка3.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-8-marinka-04",
    title: "Маринка Урок4",
    grade: 8,
    topic: "Математика",
    link: "algebra/8/Маринка/Маринка4.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },

  // ==========================================
  // 9 КЛАС (Алгебра - Соня) - Автор: Соня
  // ==========================================
  {
    id: "alg-9-sonya-func-nastya",
    title: "Функції Настя",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Функції Настя Соніна.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-sonya-func-nastya-mob",
    title: "Функції Настя телефон",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Функції Настя Соніна телефон.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-01",
    title: "Настя Урок1",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя1.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-02",
    title: "Настя Урок2",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя2.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-03",
    title: "Настя Урок3",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/теоремасинусів.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-04",
    title: "Настя Урок4",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя4.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-05",
    title: "Настя Урок5",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя5.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-06",
    title: "Настя Урок6",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя6.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-nastya-07",
    title: "Настя Урок7",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Настя7.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
  {
    id: "alg-9-artur",
    title: "Арифметична прогресія",
    grade: 9,
    topic: "Математика",
    link: "algebra/9/Настя/Артур.html",
    subject_code: "algebra",
    category: "lesson",
    author: "Соня",
  },
];
